### ISSUE TITLE
what are the improvements over the original implementation?

### ISSUE THREAD

**Issue by armheb** [Puneet-G/Impersonator-NNProject#1]
Hi thanks for sharing your project. what are the improvements over the original implementation? should we run the project as the original one?

**Comment by Puneet-G** [comment]
Hi @armheb
We were conducting an exploratory analysis, seeing if different methods would show improvements on training and inference.
Check the [report](https://github.com/Puneet-G/Impersonator-NNProject/blob/master/Final%20Report.pdf) for a full list of methods and our findings.
Take a look at the [scripts](https://github.com/Puneet-G/Impersonator-NNProject/tree/master/scripts) and runtime [options](https://github.com/Puneet-G/Impersonator-NNProject/blob/master/options/train_options.py) to see how to trigger our changes.
We also added graphing functionality to plot losses.

**Comment by armheb** [comment]
Thank you so much for the quick response!
